// 官方文档 https://eslint.org/

// @ts-check
/**
 * @type {import("eslint").Linter.Config}
 */
module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    // 使用额外的语言特性
    ecmaFeatures: {
      // 开启jsx支持
      jsx: true,
    },
    ecmaVersion: 'latest',
    sourceType: 'module',
  },
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    es2020: true,
    es2021: true,
    es2022: true,
    node: true,
  },
  extends: [
    'eslint:recommended',
    'prettier',
    'plugin:@typescript-eslint/recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:jsx-a11y/recommended',
    'plugin:prettier/recommended',
    'plugin:promise/recommended',
    'plugin:react/recommended',
    'plugin:react/jsx-runtime',
    'plugin:react-hooks/recommended',
    'plugin:sonarjs/recommended',
    'standard-with-typescript',
  ],
  plugins: [
    '@typescript-eslint',
    'eslint-comments',
    'import',
    'prettier',
    'promise',
    'react',
    'react-hooks',
    'sonarjs',
    'unicorn',
  ],
  // eslint-plugin-react的配置https://github.com/jsx-eslint/eslint-plugin-react#configuration
  settings: {
    react: {
      version: 'detect',
    },
  },
  rules: {
    '@typescript-eslint/ban-ts-comment': 'off',
    '@typescript-eslint/camelcase': 'off',
    '@typescript-eslint/consistent-type-imports': 'warn',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/lines-between-class-members': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@typescript-eslint/no-empty-interface': 'warn',
    '@typescript-eslint/no-namespace': 'off',
    '@typescript-eslint/no-non-null-assertion': 'off',
    '@typescript-eslint/no-redeclare': [2, { ignoreDeclarationMerge: true }],
    '@typescript-eslint/no-shadow': 'off',
    '@typescript-eslint/no-use-before-define': 'off',
    '@typescript-eslint/no-useless-constructor': 'off',
    '@typescript-eslint/no-unused-expressions': [
      2,
      { allowShortCircuit: true, allowTernary: true },
    ],
    '@typescript-eslint/no-unused-vars': [
      2,
      {
        vars: 'all',
        args: 'after-used',
        ignoreRestSiblings: true,
        varsIgnorePattern: 'React',
      },
    ],
    '@typescript-eslint/no-var-requires': 'off',
    '@typescript-eslint/semi': 'off',
    camelcase: 'off',
    // 是否尾随逗号
    'comma-dangle': [
      'error',
      {
        // 数组，同一行时不需要，不同行时需要
        arrays: 'always-multiline',
        exports: 'never',
        // 函数值，最后不需要尾随逗号
        functions: 'never',
        imports: 'never',
        // 对象，同一行时不需要，不同行时需要
        objects: 'always-multiline',
      },
    ],
    'consistent-return': 'off',
    'class-methods-use-this': 'off',
    'default-case-last': 'error',
    'default-param-last': 'error',
    eqeqeq: [2, 'always', { null: 'ignore' }],
    'func-names': [1, 'never', { generators: 'as-needed' }],
    'func-style': 'error',
    'import/export': 'off',
    'import/extensions': 'off',
    'import/no-cycle': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-named-as-default': 'off',
    'import/no-relative-packages': 'off',
    'import/no-unresolved': 'off',
    'import/prefer-default-export': 'off',
    'implicit-arrow-linebreak': 'off',
    'lines-between-class-members': 'off',
    'max-classes-per-file': 'off',
    'multiline-comment-style': 'error',
    'no-bitwise': 'error',
    'no-cond-assign': [2, 'except-parens'],
    'no-constructor-return': 'error',
    'no-console': 'off',
    'no-continue': 'error',
    'no-else-return': 'error',
    'no-eval': 'error',
    'no-implied-eval': 'error',
    'no-implicit-coercion': 'error',
    'no-inner-declarations': 'off',
    'no-labels': 'error',
    'no-lonely-if': 'error',
    'no-new': 'error',
    'no-promise-executor-return': 'error',
    'no-param-reassign': [2, { props: false }],
    'no-plusplus': [2, { allowForLoopAfterthoughts: true }],
    'no-redeclare': 'off',
    'no-return-assign': [2, 'except-parens'],
    'no-return-await': 'error',
    'no-shadow': 'off',
    'no-multi-assign': 'off',
    'no-nested-ternary': 'off',
    'no-unreachable-loop': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-unused-vars': 'off',
    'no-use-before-define': 'off',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'off',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'prefer-destructuring': 'off',
    'prefer-template': 'error',
    'promise/always-return': 'off',
    'promise/catch-or-return': 'off',
    'prettier/prettier': 'off',
    quotes: 'error',
    'react/destructuring-assignment': 'off',
    'react/jsx-props-no-spreading': 'off',
    'react/jsx-uses-react': 'off',
    'react/no-access-state-in-setstate': 'off',
    'react/prop-types': 'off',
    'react/react-in-jsx-scope': 'off',
    'react/self-closing-comp': 'warn',
    'react/sort-comp': 'off',
    'require-atomic-updates': 'error',
    // 总是分号结尾
    semi: ['error', 'always'],
    'sort-imports': 'off',
    'sonarjs/cognitive-complexity': 'off',
    'sonarjs/no-nested-template-literals': 'off',
    'sonarjs/no-duplicate-string': 'off',
    'sonarjs/no-small-switch': 'off',
    'sonarjs/prefer-immediate-return': 'off',
    'symbol-description': 'error',
    'require-await': 'error',
    'react-hooks/exhaustive-deps': 'warn',
    'unicorn/filename-case': 'off',
  },
};
